### ISSUE TITLE
getActivity (userService.js) - incomplete data

### ISSUE THREAD

**Issue by wulymammoth** [Fattr/fattr#69]
getActivity: function(userId, numOfDays) {
  var calculateDates = function(numOfDays) {
    var today = new Date();
    var fromDate = new Date(today - (numOfDays \* 86400000)); 
    return fromDate.toISOString().slice(0, 10) + "/" + today.toISOString().slice(0, 10);
  };
  return this._httpHelper("get", "api/user/" + calculateDates(numOfDays));
},

Not sure if the above route is correct, but this is what I'm getting back. I need to displace distance and levels (floors), but they're not contained in the JSON blob (below) that is returned from that route:

_id: "52e7483965e5540000b29d34"
date: "2014-01-26"
fairlyActiveMinutes: 72
marginalCalories: 454
sedentaryMinutes: 1236
steps: 5884
user: "52e3f5e23b84f1cb5f285342"
veryActiveMinutes: 9

**Comment by Hendrixer** [comment]
I'll fix it

**Comment by wulymammoth** [comment]
sweet. just wanted to test "issues" to see if I knew how to submit one.
haha.

**Comment by sarchila** [comment]
Not sure if this is already fixed on your local machine, but when I hit the /api/user route with no start and end dates (default), I get this:

{
  "username": "test",
  "stats": [
    {
      "sedentaryMinutes": 598,
      "marginalCalories": 655,
      "steps": 7153,
      "user": "52e80ade85ab51c37744c0ec",
      "_id": "52e80afc85ab51c37744c0ed",
      "__v": 0
    },
    {
      "sedentaryMinutes": 598,
      "marginalCalories": 655,
      "steps": 7153,
      "user": "52e80ade85ab51c37744c0ec",
      "_id": "52e80b9085ab51c37744c0ee",
      "__v": 0
    },
    {
      "sedentaryMinutes": 598,
      "marginalCalories": 655,
      "steps": 7153,
      "user": "52e80ade85ab51c37744c0ec",
      "_id": "52e80bd725fb4ba879378f65",
      "__v": 0
    },
    {
      "sedentaryMinutes": 598,
      "marginalCalories": 655,
      "steps": 7153,
      "user": "52e80ade85ab51c37744c0ec",
      "_id": "52e80c34a0434f5e7a87c342",
      "__v": 0
    }
  ]
}

The problem I see is that this is the same exact stat saved as four separate objects, and I'm not sure what date it comes from.
